apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "monitoring-secrets.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Storage configurations
  grafana-storage-size: {{ .Values.storage.grafana.size | quote }}
  prometheus-storage-size: {{ .Values.storage.prometheus.size | quote }}
  alertmanager-storage-size: {{ .Values.storage.alertmanager.size | quote }}
  {{- if .Values.storage.grafana.storageClassName }}
  grafana-storage-class: {{ .Values.storage.grafana.storageClassName | quote }}
  {{- end }}
  {{- if .Values.storage.prometheus.storageClassName }}
  prometheus-storage-class: {{ .Values.storage.prometheus.storageClassName | quote }}
  {{- end }}
  
  # Retention settings
  prometheus-retention: {{ .Values.retention.prometheus | quote }}
  alertmanager-retention: {{ .Values.retention.alertmanager | quote }}
  
  # Service configurations
  service-type: {{ .Values.service.type | quote }}
  grafana-node-port: {{ .Values.service.grafana.nodePort | quote }}
  prometheus-node-port: {{ .Values.service.prometheus.nodePort | quote }}
  alertmanager-node-port: {{ .Values.service.alertmanager.nodePort | quote }}
  
  # Resource configurations
  grafana-cpu-requests: {{ .Values.resources.grafana.requests.cpu | quote }}
  grafana-memory-requests: {{ .Values.resources.grafana.requests.memory | quote }}
  grafana-cpu-limits: {{ .Values.resources.grafana.limits.cpu | quote }}
  grafana-memory-limits: {{ .Values.resources.grafana.limits.memory | quote }}
  
  prometheus-cpu-requests: {{ .Values.resources.prometheus.requests.cpu | quote }}
  prometheus-memory-requests: {{ .Values.resources.prometheus.requests.memory | quote }}
  prometheus-cpu-limits: {{ .Values.resources.prometheus.limits.cpu | quote }}
  prometheus-memory-limits: {{ .Values.resources.prometheus.limits.memory | quote }}
  
  alertmanager-cpu-requests: {{ .Values.resources.alertmanager.requests.cpu | quote }}
  alertmanager-memory-requests: {{ .Values.resources.alertmanager.requests.memory | quote }}
  alertmanager-cpu-limits: {{ .Values.resources.alertmanager.limits.cpu | quote }}
  alertmanager-memory-limits: {{ .Values.resources.alertmanager.limits.memory | quote }}