apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "monitoring-secrets.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  {{- if .Values.grafana.admin.password }}
  grafana-admin-user: {{ .Values.grafana.admin.user | b64enc }}
  grafana-admin-password: {{ .Values.grafana.admin.password | b64enc }}
  {{- else }}
  # IMPORTANT: Set grafana.admin.password via ArgoCD parameter
  # --helm-set grafana.admin.password=YourSecurePassword123
  grafana-admin-user: {{ .Values.grafana.admin.user | b64enc }}
  grafana-admin-password: {{ "PLEASE_SET_VIA_ARGOCD_PARAMETER" | b64enc }}
  {{- end }}