# Grafana configuration template
# Sensitive values should be set via ArgoCD helm parameters

grafana:
  # Admin credentials - SET VIA ARGOCD PARAMETERS
  # --helm-set grafana.adminUser=admin
  # --helm-set grafana.adminPassword=YOUR_SECURE_PASSWORD
  adminUser: admin
  # adminPassword: # Set via ArgoCD parameter
  
  # Persistent storage - CONFIGURABLE VIA PARAMETERS
  # --helm-set grafana.persistence.enabled=true
  # --helm-set grafana.persistence.size=10Gi
  # --helm-set grafana.persistence.storageClassName=standard
  persistence:
    enabled: false  # Override via parameter
    # size: 10Gi    # Set via parameter
    # storageClassName: standard  # Set via parameter
  
  # Service configuration - CONFIGURABLE VIA PARAMETERS
  # --helm-set grafana.service.type=NodePort
  # --helm-set grafana.service.nodePort=30300
  service:
    type: ClusterIP  # Default, override via parameter
    port: 80
    # nodePort: # Set via parameter when type=NodePort
  
  # Grafana configuration - DYNAMIC BASED ON PARAMETERS
  grafana.ini:
    server:
      # domain and root_url will be set based on service configuration
      serve_from_sub_path: false
    
    security:
      # admin_user and admin_password set via helm parameters
      allow_embedding: true
    
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_role: Viewer
    
    auth.anonymous:
      enabled: false
  
  # Default plugins to install
  plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel
    - grafana-clock-panel
  
  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  # Default dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  
  # Datasources - ready for Prometheus integration
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: TestData DB
        type: testdata
        access: proxy
        isDefault: true